### ISSUE TITLE
Swap echo by chi

### ISSUE THREAD

**Issue by guiferpa** [michelaquino/golang_api_skeleton#7]
This [Echo](https://github.com/labstack/echo) is so good, but [Chi](https://github.com/pressly/chi) is 100 percent from http package standard. Look the [Chi](https://github.com/pressly/chi), maybe you like it.

**Comment by michelaquino** [comment]
Hy @guiferpa 
Thanks for the suggestion. But for now I will use [Echo](https://github.com/labstack/echo)
👍
